[tool.poetry]
name = "dlt-cert"
version = "0.1.0"
description = ""
authors = ["rafael.amorim <raffaekk@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
dlt = "^1.18.2"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
